name: genesys-messenger-route-demo

services:
  genesys-messenger-route-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genesys-messenger-route-demo
    restart: unless-stopped
    ports:
      - "127.0.0.1:18088:80"
    mem_limit: 128m
    cpus: "0.25"

# If this mockup needs to communicate with internal backends in the future,
# you can uncomment the network settings below to hook into the proxy network.
# networks:
#   internal_services_net:
#     external: true
