name: genesys-messenger-route-demo

services:
  # 1. Maqueta Web Estática (Servidor Nginx interno)
  genesys-messenger-route-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genesys-messenger-route-demo
    restart: unless-stopped
    # Exponemos el puerto 80 únicamente a la red interna de Docker
    expose:
      - "80"
    mem_limit: 128m
    cpus: "0.25"

  # 2. Proxy Inverso con SSL Automático (Caddy)
  caddy:
    image: caddy:alpine
    container_name: caddy-ssl-proxy
    restart: unless-stopped
    # Mapeamos los puertos públicos estándar para HTTP y HTTPS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - genesys-messenger-route-demo

# Volúmenes persistentes para almacenar certificados SSL y configuraciones de Caddy
volumes:
  caddy_data:
  caddy_config:
